services:
  frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: stivenc30/cropco-frontend:latest
    # image: cropco-frontend:latest
    container_name: cropco-frontend
    ports:
      - '${PORT:-80}:80'
    environment:
      - VITE_HOST_API_CROPCO=${VITE_HOST_API_CROPCO}
      - VITE_STATUS_PROJECT=${VITE_STATUS_PROJECT}
    restart: unless-stopped
    networks:
      - cropco-network

networks:
  cropco-network:
    name: cropco-network
