export const defaultGlobalActionsUserAdmin = {
  clients: {
    create_client: false,
    find_all_clients: false,
    find_all_clients_with_sales: false,
    find_one_client: false,
    update_one_client: false,
    remove_one_client: false,
    remove_bulk_clients: false,
    export_clients_pdf: false,
  },
  crops: {
    create_crop: false,
    find_all_crops: false,
    find_one_crop: false,
    find_all_crops_with_harvest: false,
    find_all_crops_with_work: false,
    find_all_crops_with_sales: false,
    find_all_crops_with_consumptions: false,
    update_one_crop: false,
    remove_one_crop: false,
    remove_bulk_crops: false,
    find_all_crops_stock: false,
  },
  employees: {
    create_employee: false,
    find_all_employees: false,
    find_all_employees_with_pending_payments: false,
    find_all_employees_with_made_payments: false,
    find_one_employee_with_pending_payments: false,
    find_all_employees_with_harvests: false,
    find_all_employees_with_works: false,
    find_one_employee: false,
    update_one_employee: false,
    remove_one_employee: false,
    remove_bulk_employees: false,
    find_certification_employee: false,
    find_top_employees_in_harvests: false,
    find_top_employees_in_works: false,
  },
  harvests: {
    create_harvest: false,
    create_harvest_processed: false,
    find_all_harvests: false,
    find_one_harvest: false,
    find_one_harvest_processed_all: false,
    update_one_harvest: false,
    update_one_harvest_processed: false,
    remove_one_harvest: false,
    remove_bulk_harvests: false,
    remove_one_harvest_processed: false,
    export_harvest_to_pdf: false,
  },
  payments: {
    create_payment: false,
    find_all_payments: false,
    find_one_payment: false,
    remove_one_payment: false,
    remove_bulk_payments: false,
    export_payment_to_pdf: false,
  },
  sales: {
    create_sale: false,
    find_all_sales: false,
    find_one_sale: false,
    update_one_sale: false,
    remove_one_sale: false,
    remove_bulk_sales: false,
    export_sale_to_pdf: false,
  },
  suppliers: {
    create_supplier: false,
    find_all_suppliers: false,
    find_all_suppliers_with_shopping: false,
    find_one_supplier: false,
    update_one_supplier: false,
    remove_one_supplier: false,
    remove_bulk_suppliers: false,
  },
  supplies: {
    create_supply: false,
    find_all_supplies: false,
    find_all_supplies_with_shopping: false,
    find_all_supplies_with_consumptions: false,
    find_all_supplies_with_stock: false,
    find_one_supply: false,
    update_one_supply: false,
    remove_one_supply: false,
    remove_bulk_supplies: false,
  },
  consumptions: {
    create_supply_consumption: false,
    find_all_supplies_consumption: false,
    find_one_supplies_consumption: false,
    update_one_supplies_consumption: false,
    remove_one_supplies_consumption: false,
    remove_bulk_supplies_consumption: false,
  },
  shopping: {
    create_supply_shopping: false,
    find_all_supplies_shopping: false,
    find_one_supplies_shopping: false,
    update_one_supplies_shopping: false,
    remove_one_supplies_shopping: false,
    remove_bulk_supplies_shopping: false,
    export_shopping_to_pdf: false,
  },
  users: {
    create_user: false,
    find_all_users: false,
    find_one_user: false,
    update_one_user: false,
    remove_one_user: false,
    remove_bulk_users: false,
    reset_password_user: false,
    change_password_user: false,
    toggle_status_user: false,
  },
  works: {
    create_work: false,
    find_all_works: false,
    find_one_work: false,
    update_one_work: false,
    remove_one_work: false,
    remove_bulk_works: false,
    export_work_to_pdf: false,
  },
  dashboard: {
    find_top_employees_in_harvests_chart: false,
    find_top_employees_in_works_chart: false,
    find_all_crops_stock_chart: false,
    find_top_clients_in_sales_chart: false,
    find_count_harvests_and_total_stock_chart: false,
    find_total_harvest_in_year_chart: false,
    find_total_work_in_year_chart: false,
    find_total_sales_in_year_chart: false,
    find_total_consumptions_in_year_chart: false,
  },
};
