export const defaultGlobalActionsUserAdmin = {
  clients: {
    create_client: true,
    find_all_clients: true,
    find_all_clients_with_sales: true,
    find_one_client: true,
    update_one_client: true,
    remove_one_client: true,
    remove_bulk_clients: true,
    export_clients_pdf: true,
  },
  crops: {
    create_crop: true,
    find_all_crops: true,
    find_one_crop: true,
    find_all_crops_with_harvest: true,
    find_all_crops_with_work: true,
    find_all_crops_with_sales: true,
    find_all_crops_with_consumptions: true,
    update_one_crop: true,
    remove_one_crop: true,
    remove_bulk_crops: true,
    find_all_crops_stock: true,
  },
  employees: {
    create_employee: true,
    find_all_employees: true,
    find_all_employees_with_pending_payments: true,
    find_all_employees_with_made_payments: true,
    find_one_employee_with_pending_payments: true,
    find_all_employees_with_harvests: true,
    find_all_employees_with_works: true,
    find_one_employee: true,
    update_one_employee: true,
    remove_one_employee: true,
    remove_bulk_employees: true,
    find_certification_employee: true,
    find_top_employees_in_harvests: true,
    find_top_employees_in_works: true,
  },
  harvests: {
    create_harvest: true,
    create_harvest_processed: true,
    find_all_harvests: true,
    find_one_harvest: true,
    find_one_harvest_processed_all: true,
    update_one_harvest: true,
    update_one_harvest_processed: true,
    remove_one_harvest: true,
    remove_bulk_harvests: true,
    remove_one_harvest_processed: true,
    export_harvest_to_pdf: true,
  },
  payments: {
    create_payment: true,
    find_all_payments: true,
    find_one_payment: true,
    remove_one_payment: true,
    remove_bulk_payments: true,
    export_payment_to_pdf: true,
  },
  sales: {
    create_sale: true,
    find_all_sales: true,
    find_one_sale: true,
    update_one_sale: true,
    remove_one_sale: true,
    remove_bulk_sales: true,
    export_sale_to_pdf: true,
  },
  suppliers: {
    create_supplier: true,
    find_all_suppliers: true,
    find_all_suppliers_with_shopping: true,
    find_one_supplier: true,
    update_one_supplier: true,
    remove_one_supplier: true,
    remove_bulk_suppliers: true,
  },
  supplies: {
    create_supply: true,
    find_all_supplies: true,
    find_all_supplies_with_shopping: true,
    find_all_supplies_with_consumptions: true,
    find_all_supplies_with_stock: true,
    find_one_supply: true,
    update_one_supply: true,
    remove_one_supply: true,
    remove_bulk_supplies: true,
  },
  consumptions: {
    create_supply_consumption: true,
    find_all_supplies_consumption: true,
    find_one_supplies_consumption: true,
    update_one_supplies_consumption: true,
    remove_one_supplies_consumption: true,
    remove_bulk_supplies_consumption: true,
  },
  shopping: {
    create_supply_shopping: true,
    find_all_supplies_shopping: true,
    find_one_supplies_shopping: true,
    update_one_supplies_shopping: true,
    remove_one_supplies_shopping: true,
    remove_bulk_supplies_shopping: true,
    export_shopping_to_pdf: true,
  },
  users: {
    create_user: true,
    find_all_users: true,
    find_one_user: true,
    update_one_user: true,
    remove_one_user: true,
    remove_bulk_users: true,
    reset_password_user: true,
    change_password_user: true,
    toggle_status_user: true,
  },
  works: {
    create_work: true,
    find_all_works: true,
    find_one_work: true,
    update_one_work: true,
    remove_one_work: true,
    remove_bulk_works: true,
    export_work_to_pdf: true,
  },
  dashboard: {
    find_top_employees_in_harvests_chart: true,
    find_top_employees_in_works_chart: true,
    find_all_crops_stock_chart: true,
    find_top_clients_in_sales_chart: true,
    find_count_harvests_and_total_stock_chart: true,
    find_total_harvest_in_year_chart: true,
    find_total_work_in_year_chart: true,
    find_total_sales_in_year_chart: true,
    find_total_consumptions_in_year_chart: true,
  },
};
