// Generated by https://quicktype.io

import { UnitOfMeasureHarvest } from '@/enums/UnitOfMeasure';
import { ObjectWithId } from './ObjectWithId';

export interface Harvest {
  id?: string;
  date: Date;
  crop: ObjectWithId;
  unit_of_measure: UnitOfMeasureHarvest | string;
  total: number;
  value_pay: number;
  observation?: string | undefined;
  details: HarvestDetail[];
}

export interface HarvestDetail {
  id?: string;
  employee: ObjectWithId;
  total: number;
  value_pay: number;
}

export interface TableHarvest {
  id?: string;
  date: string;
  crop: string;
  unit_of_measure: UnitOfMeasureHarvest;
  total: number;
  value_pay: number;
}
