// Generated by https://quicktype.io

import { UnitOfMeasureHarvest } from '@/enums/UnitOfMeasure';

export interface Harvest {
  id?: string;
  date: Date;
  crop: string;
  unit_of_measure: UnitOfMeasureHarvest | string;
  total: number;
  value_pay: number;
  observation: string;
  details: HarvestDetail[];
}

export interface HarvestDetail {
  id?: string;
  employee: string | undefined;
  total: number;
  value_pay: number;
}

export interface TableHarvest {
  id?: string;
  date: string;
  crop: string;
  unit_of_measure: UnitOfMeasureHarvest;
  total: number;
  value_pay: number;
}
